menu:
    Blog: /
    Products: /products/
    Archives: /archives/
    About: /about/
    Instagram: https://instagram.com/linroid/

favicon: /favicon.ico
logo: /avatar.png

# Comment
# e.g disqus: seansun
disqus: linroid
duoshuo:

# Analytics
# google-analytics:
ga: UA-50624084-1

# Copyright Infomation
startyear: 2013
